baseURL = 'andywells.dev'
languageCode = 'en-us'
title = 'Andy Wells'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Andy Wells"
subtitle = "Computer engineering student and electronics hobbyist"
imageUrl = "/media/Hiking2.jpg"
imageWidth = 134
imageHeight = 120
imageTitle = "Hiking Photo"

  [[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects/"

  [[params.profileMode.buttons]]
  name = "Resume"
  url = "/cv/"

  [[params.profileMode.buttons]]
  name = "AboutMe"
  url = "/about/"

[[menu.main]]
identifier = 'Projects'
name = 'Projects'
url = '/projects/'
weight = '50'

[[menu.main]]
identifier = 'CV'
name = 'CV'
url = '/cv/'
weight = '50'

[[menu.main]]
identifier = 'AboutMe'
name = 'AboutMe'
url = '/about/'
weight = '50'



