baseURL = 'andywells.dev'
languageCode = 'en-us'
title = 'Andy Wells Personal Site'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Andy Wells"
subtitle = "Computer engineering student and electronics hobbyist"
imageUrl = "/media/ProfilePhoto.png"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

  [[params.profileMode.buttons]]
  name = "Projects"
  url = "/post/"

  [[params.profileMode.buttons]]
  name = "Resume"
  url = "/cv/"

  [[params.profileMode.buttons]]
  name = "AboutMe"
  url = "/about/"

[[menu.main]]
identifier = 'Projects'
name = 'Projects'
url = '/post/'
weight = '50'

[[menu.main]]
identifier = 'CV'
name = 'CV'
url = '/cv/'
weight = '50'

[[menu.main]]
identifier = 'AboutMe'
name = 'AboutMe'
url = '/about/'
weight = '50'



